name: build-test
on: [push]
jobs:
  build:
    name: solution
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.1.21103.13'
      - run: dotnet --version
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.4, 16.9]'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      # - name: Restore NuGet Packages
      #   run: nuget restore helpsharp.sln
      - name: Build
        run: msbuild helpsharp.sln /p:Configuration=Release
