name: build-test
on: [push]
jobs:
  build:
    name: solution
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: True
      - name: dotnet commands
        run: |
              dotnet --version
              dotnet --info
              dotnet --list-sdks
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.9, 16.10)'
      - name: Choco install netcorebuildtools
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install visualstudio2019-workload-netcorebuildtools --no-progress
        if: runner.os == 'Windows'
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      - name: Restore NuGet Packages
        run: nuget restore helpsharp.sln
      - run: dotnet nuget locals all -c
      - name: Build
        run: msbuild helpsharp.sln /p:Configuration=Release
